import { createStore } from 'vuex'
import actions from './actions';
import mutations from './mutations'

//modules
import NavHome from './Modules/NavHome'
import NavMenu from './Modules/NavMenu'
import HomeImages from './Modules/HomeImages'
import algorithm from './Modules/Algorithm'
import table from './Modules/Table'

export default createStore({
  state: {
   javaItem:[
     {id:1,header:'Android',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them',imgurl:'/../../../../images/11.jpg'},
     {id:2,header:'REST Pagination in Spring',text:'Treating the page itself as a resource introduces a host of problems such as no longer being able to uniquely identify resources between calls. This, coupled with the fact that, in the persistence layer, the page is not a proper entity but a holder that is constructed when necessary, makes the choice straightforward: the page is part of the representation',imgurl:'/../../../../images/12.jpg'},
     {id:3,header:' The Controller',text:'Alternatively, we could have used a Pageable object, which maps the page, size, and sort parameters automatically. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/13.jpg'},
     {id:4,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/13.jpg'},
     {id:5,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/14.jpg'},
     {id:6,header:'Test Driving Pagination Discoverability',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/12.jpg'},
     {id:7,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/15.jpg'},
     {id:8,header:'Getting All Resources',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/11.jpg'},
     {id:9,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/8.jpg'},
     {id:10,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/3.jpg'},
     {id:11,header:' REST Paging With Range HTTP Headers',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/1.jpg'},
     {id:12,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/5.jpg'},
     {id:13,header:'Convert a List into a Page',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/7.jpg'},
     {id:14,header:' Conclusion',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/8.jpg'},
     {id:15,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/12.jpg'},
   ],
   leftSideItem:[
     {id:1,header:'computer',showLink:true,parts:[
          {id:1,linkText:'Software',router:'/bookhome/'},
          {id:2,linkText:'hardware',router:'/bookhome/hardware'},
          {id:3,linkText:'Data Sicentis',router:'/bookhome/datasintis'},
     ]},
     {id:2,header:'Ai',parts:[
          {id:1,linkText:'A*',showLink:true,router:'/bookhome/'},
          {id:2,linkText:'Genetic',router:'/bookhome/'},
          {id:3,linkText:'recovery',router:'/bookhome/'},
     ]},
   ],
   softwareRside:[
     {id:500,href:'500',title:'enterprise',textCtn:'Meet Jira Service Management',mainCtn:'Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.'},
     {id:501,href:'501',title:'Make work visible',textCtn:'Connect Dev and Ops',mainCtn:'“Jira Service Management supports our processes so we all work in the same tool, in the same way...Now we have a single place of truth from which we can extract data and base our reports. This provides us with a better overview and a common understanding throughout the organization."'},
     {id:502,href:'502',title:'manual processes',textCtn:'Easily navigate and search content',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:503,href:'503',title:'Meet corporate ',textCtn:'CARA workflows can be configured to mandate specific processes',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:504,href:'504',title:'regulatory standards',textCtn:'Easily navigate and search content',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
   ]
  },
  getters:{

  },
  actions,
  mutations,
  modules: {
   a:NavHome,
   b:NavMenu,
   c:HomeImages,
   d:algorithm,
   tbl:table
  }
})
