import { createStore } from 'vuex'
import actions from './actions';
import mutations from './mutations'

//modules
import NavHome from './Modules/NavHome'
import NavMenu from './Modules/NavMenu'
import HomeImages from './Modules/HomeImages'
import algorithm from './Modules/Algorithm'
import table from './Modules/Table'

export default createStore({
  state: {
   javaItem:[
     {id:1,header:'Android',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them',imgurl:'/../../../../images/11.jpg'},
     {id:2,header:'REST Pagination in Spring',text:'Treating the page itself as a resource introduces a host of problems such as no longer being able to uniquely identify resources between calls. This, coupled with the fact that, in the persistence layer, the page is not a proper entity but a holder that is constructed when necessary, makes the choice straightforward: the page is part of the representation',imgurl:'/../../../../images/12.jpg'},
     {id:3,header:' The Controller',text:'Alternatively, we could have used a Pageable object, which maps the page, size, and sort parameters automatically. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/13.jpg'},
     {id:4,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/13.jpg'},
     {id:5,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/14.jpg'},
     {id:6,header:'Test Driving Pagination Discoverability',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/12.jpg'},
     {id:7,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/15.jpg'},
     {id:8,header:'Getting All Resources',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/11.jpg'},
     {id:9,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/8.jpg'},
     {id:10,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/3.jpg'},
     {id:11,header:' REST Paging With Range HTTP Headers',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/1.jpg'},
     {id:12,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/5.jpg'},
     {id:13,header:'Convert a List into a Page',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/7.jpg'},
     {id:14,header:' Conclusion',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/8.jpg'},
     {id:15,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/12.jpg'},
   ]
  },
  getters:{

  },
  actions,
  mutations,
  modules: {
   a:NavHome,
   b:NavMenu,
   c:HomeImages,
   d:algorithm,
   tbl:table
  }
})
