import { createStore } from 'vuex'
import actions from './actions';
import mutations from './mutations'

//modules
import NavHome from './Modules/NavHome'
import NavMenu from './Modules/NavMenu'
import HomeImages from './Modules/HomeImages'
import algorithm from './Modules/Algorithm'
import table from './Modules/Table'
import astar from './Modules/AStart'
import carIndex from './Modules/CarIndex'
import pagination from './Modules/Pagination'

export default createStore({
  state: {
   javaItem:[
     {id:1,header:'Android',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them',imgurl:'/../../../../images/11.jpg'},
     {id:2,header:'REST Pagination in Spring',text:'Treating the page itself as a resource introduces a host of problems such as no longer being able to uniquely identify resources between calls. This, coupled with the fact that, in the persistence layer, the page is not a proper entity but a holder that is constructed when necessary, makes the choice straightforward: the page is part of the representation',imgurl:'/../../../../images/12.jpg'},
     {id:3,header:' The Controller',text:'Alternatively, we could have used a Pageable object, which maps the page, size, and sort parameters automatically. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/13.jpg'},
     {id:4,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/13.jpg'},
     {id:5,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/14.jpg'},
     {id:6,header:'Test Driving Pagination Discoverability',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/12.jpg'},
     {id:7,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/15.jpg'},
     {id:8,header:'Getting All Resources',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/11.jpg'},
     {id:9,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/8.jpg'},
     {id:10,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/3.jpg'},
     {id:11,header:' REST Paging With Range HTTP Headers',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/1.jpg'},
     {id:12,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/5.jpg'},
     {id:13,header:'Convert a List into a Page',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/7.jpg'},
     {id:14,header:' Conclusion',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/8.jpg'},
     {id:15,header:'Test Driving Pagination',text:'Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.. In addition, the PagingAndSortingRepository entity provides out-of-the-box methods that support using the Pageable as a parameter as well.',imgurl:'/../../../../images/12.jpg'},
   ],
   leftSideItem:[
     {id:1,header:'computer',showLink:true,parts:[
          {id:1,linkText:'Software',router:'/home/bookhome/'},
          {id:2,linkText:'hardware',router:'/home/bookhome/hardware'},
          {id:3,linkText:'Data Sicentis',router:'/home/bookhome/datasintis'},
     ]},
     {id:2,header:'Ai',parts:[
          {id:1,linkText:'A*',showLink:true,router:'/home/bookhome/astart'},
          {id:2,linkText:'Genetic',router:'/home/bookhome/genetic'},
          {id:3,linkText:'recovery',router:'/home/bookhome/recovery'},
     ]},
   ],
   softwareRside:[
     {id:500,href:'500',title:'enterprise',textCtn:'Meet Jira Service Management',mainCtn:'Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.Click Insert and then choose the elements you want from the different galleries. Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. Save time in Word with new buttons that show up where you need them.'},
     {id:501,href:'501',title:'Make work visible',textCtn:'Connect Dev and Ops',mainCtn:'“Jira Service Management supports our processes so we all work in the same tool, in the same way...Now we have a single place of truth from which we can extract data and base our reports. This provides us with a better overview and a common understanding throughout the organization."'},
     {id:502,href:'502',title:'manual processes',textCtn:'Easily navigate and search content',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:503,href:'503',title:'Meet corporate ',textCtn:'CARA workflows can be configured to mandate specific processes',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:504,href:'504',title:'regulatory standards',textCtn:'Easily navigate and search content',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes 1',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes 2',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes 3',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes ',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes5',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes 6',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes 8',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes 9',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes 12',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
     {id:505,href:'505',title:'manual processes',textCtn:'from creation to access, search, review, approval and publication',mainCtn:'Generis has led innovation in content and data solutions for over 20 years. Trusted across regulated industries, Generis provides content management solutions and services globally, to help you streamline your processes and reduce costs while improving efficiency'},
   ],
   navHardware:[
     {id:1,headerLink:'Architecture',showLink:true,parts:
    [
      {id:1,textLink:'Page one',router:'/home/bookhome/hardware/'},
      {id:2,textLink:'Page two',router:'/home/bookhome/hardware/hardwarepage2'},
      {id:3,textLink:'Page three',router:'/home/bookhome/hardware/'},
      {id:4,textLink:'Page four',router:'/home/bookhome/hardware/hardwarepage2'},
      {id:5,textLink:'Page five',router:'/home/bookhome/hardware/'},
    ]}
   ],
   hardwarePage1:[
     {id:1,url:'../../../image-hw/1.jpg',alt:'image 1',imgText:'image 1',router:'/home/bookhome/hardware/hardwarepage2'},
     {id:2,url:'../../../image-hw/2.jpg',alt:'image 2',imgText:'image 2',router:'/home/bookhome/hardware/hardwarepage2'},
     {id:3,url:'../../../image-hw/3.jpg',alt:'image 3',imgText:'image 3',router:'/home/bookhome/hardware/hardwarepage2'},
     {id:4,url:'../../../image-hw/4.jpg',alt:'image 4',imgText:'image 4',router:'/home/bookhome/hardware/hardwarepage2'},
     {id:5,url:'../../../image-hw/5.jpg',alt:'image 5',imgText:'image 5',router:'/home/bookhome/hardware/hardwarepage2'},
     {id:6,url:'../../../image-hw/6.jpg',alt:'image 6',imgText:'image 6',router:'/home/bookhome/hardware/hardwarepage2'},
     {id:7,url:'../../../image-hw/7.jpg',alt:'image 7',imgText:'image 7',router:'/home/bookhome/hardware/hardwarepage2'},
     {id:8,url:'../../../image-hw/8.jpg',alt:'image 8',imgText:'image 8',router:'/home/bookhome/hardware/hardwarepage2'},
     {id:9,url:'../../../image-hw/9.jpg',alt:'image 9',imgText:'image 9',router:'/home/bookhome/hardware/hardwarepage2'},
     {id:10,url:'../../../image-hw/1.jpg',alt:'image 10',imgText:'image 10 ',router:'/home/bookhome/hardware/hardwarepage2'},
     {id:11,url:'../../../image-hw/7.jpg',alt:'image 11',imgText:'image 11',router:'/home/bookhome/hardware/hardwarepage2'},
     {id:12,url:'../../../image-hw/3.jpg',alt:'image 12',imgText:'image 12',router:'/home/bookhome/hardware/hardwarepage2'},
     {id:13,url:'../../../image-hw/4.jpg',alt:'image 13',imgText:'image 13',router:'/home/bookhome/hardware/hardwarepage2'},
     {id:14,url:'../../../image-hw/5.jpg',alt:'image 14',imgText:'image 14',router:'/home/bookhome/hardware/hardwarepage2'},
     {id:15,url:'../../../image-hw/1.jpg',alt:'image 15',imgText:'image 15',router:'/home/bookhome/hardware/hardwarepage2'},
   ],
   hardwarePage2:[
     {id:1,url:'../../../image-hw2/11.jpg',alt:'image 1',imgText:'image one',router:'/home/bookhome/hardware/'},
     {id:2,url:'../../../image-hw2/10.jpg',alt:'image 2',imgText:'image two',router:'/home/bookhome/hardware/'},
     {id:3,url:'../../../image-hw2/3.jpg',alt:'image 3',imgText:'image three',router:'/home/bookhome/hardware/'},
     {id:4,url:'../../../image-hw2/4.jpg',alt:'image 4',imgText:'image four',router:'/home/bookhome/hardware/'},
     {id:5,url:'../../../image-hw2/1.jpg',alt:'image 5',imgText:'image five',router:'/home/bookhome/hardware/'},
     {id:6,url:'../../../image-hw2/9.jpg',alt:'image 6',imgText:'image six',router:'/home/bookhome/hardware/'},
     {id:7,url:'../../../image-hw2/7.jpg',alt:'image 7',imgText:'image seven',router:'/home/bookhome/hardware/'},
     {id:8,url:'../../../image-hw2/2.jpg',alt:'image 8',imgText:'image eight',router:'/home/bookhome/hardware/'},
     {id:9,url:'../../../image-hw2/9.jpg',alt:'image 9',imgText:'image nine',router:'/home/bookhome/hardware/'},
     {id:10,url:'../../../image-hw2/1.jpg',alt:'image 10',imgText:'image ten',router:'/home/bookhome/hardware/'},
     {id:11,url:'../../../image-hw2/7.jpg',alt:'image 11',imgText:'image eleven',router:'/home/bookhome/hardware/'},
     {id:12,url:'../../../image-hw2/10.jpg',alt:'image 12',imgText:'image twleve',router:'/home/bookhome/hardware/'},
     {id:13,url:'../../../image-hw2/4.jpg',alt:'image 13',imgText:'image thirteen',router:'/home/bookhome/hardware/'},
     {id:14,url:'../../../image-hw2/3.jpg',alt:'image 14',imgText:'image fouteen',router:'/home/bookhome/hardware/'},
     {id:15,url:'../../../image-hw2/1.jpg',alt:'image 15',imgText:'image fiveteen',router:'/home/bookhome/hardware/'},
   ],
   recoverImageItem:[
     {id:1,url:'../../image-as/cloth1.png',text:'Learn about breast and ovarian health and assess your risk.',routerText:'TAKE OUR 5 MINUTE QUIZ',router:'/bookhome/recovery'},
     {id:2,url:'../../image-as/cloth2.png',text:'Explore resources for women at increased risk of breast & ovarian cancer..',routerText:'CONNECT TO SUPPORT',router:'/bookhome/recovery'},
     {id:3,url:'../../image-as/cloth3.png',text:'Make a gift or start a fundraiser to fuel our life-saving mission.',routerText:'DONATE',router:'/bookhome/recovery'},
   ]
  },
  getters:{

  },
  actions,
  mutations,
  modules: {
   a:NavHome,
   b:NavMenu,
   c:HomeImages,
   d:algorithm,
   tbl:table,
   ast:astar,
   carIndex:carIndex,
   pag:pagination
  }
})
