const state={
    alItem:[
        {id:1,imgurl:'/../../../../imagebook/1.jpg',title:'َAlgorithm & flowchart',price:' Posted on February 19, 2016 500$',breif:'matris Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.'},
        {id:2,imgurl:'/../../../../imagebook/2.jpg',title:'Base of Algorithm',price:' Posted on February 12, 2016 600$',breif:'mul Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.'},
        {id:2,imgurl:'/../../../../imagebook/3.jpg',title:'computing',price:' Posted on February 19, 2016 500$',breif:'mul Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.'},
        {id:2,imgurl:'/../../../../imagebook/4.jpg',title:'Software engineering',price:' Posted on February 19, 2016 300$',breif:'mul Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.'},
        {id:2,imgurl:'/../../../../imagebook/5.jpg',title:'another example 1',price:' Posted on February 19, 2016 500$',breif:'anoher Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.'},
        {id:2,imgurl:'/../../../../imagebook/6.jpg',title:'another example 2',price:' Posted on February 5, 2016 750$',breif:'anoher Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.'},
        {id:2,imgurl:'/../../../../imagebook/8.jpg',title:'another example 3',price:' Posted on February 19, 2016 500$',breif:'anoher Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.'},
        {id:2,imgurl:'/../../../../imagebook/1.jpg',title:'another example 4',price:' Posted on February 19, 2020 500$',breif:'anoher Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.'},
        {id:2,imgurl:'/../../../../imagebook/2.jpg',title:'another example 5',price:' Posted on February 3, 2016 300$',breif:'anoher Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.'},
        {id:2,imgurl:'/../../../../imagebook/4.jpg',title:'another example 6',price:' Posted on February 19, 2016 500$',breif:'anoher Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.'},
        {id:2,imgurl:'/../../../../imagebook/5.jpg',title:'another example 7',price:' Posted on February 19, 2018 500$',breif:'anoher Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.'},
        {id:2,imgurl:'/../../../../imagebook/6.jpg',title:'another example 8',price:' Posted on February 2, 2016 500$',breif:'anoher Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.'},
        {id:2,imgurl:'/../../../../imagebook/2.jpg',title:'another example 9',price:' Posted on February 19, 2016 500$',breif:'anoher Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.'},
        {id:2,imgurl:'/../../../../imagebook/1.jpg',title:'another example 10',price:' Posted on February 19, 2000 500$',breif:'anoher Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.'},
        {id:2,imgurl:'/../../../../imagebook/4.jpg',title:'another example 1',price:' Posted on February 19, 2016 500$',breif:'anoher Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar.'},
    ]
};

const getters={};

const mutations={}

const actions={};

export default {
    state,
    getters,
    mutations,
    actions
}